os:
  linux

dist:
  xenial

services:
  - postgresql
  - mysql

language:
  python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - cp .env.example .env
  - psql -c 'CREATE DATABASE test;' -U postgres
  - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;'

install:
  - make install

script:
  - make test-ci

after_success:
  - coveralls

jobs:
  include:
    - stage: release
      if: tag IS present
      python: 3.8
      deploy:
        edge: true
        provider: pypi
        user: roll
        distributions: sdist bdist_wheel
        on:
          tags: true
        password:
          secure: ml6AOxe33nZ3l30x9K1T1xbPVGSVsnMrB88azVTmhswt9T6C5LcHJBwWHB1BNWS4Gc0rbYMWjdEXlTlyzJgqkHTCFWQCmHnwYTWWhWpxV9f5heljGGeBZQlwl2KNB8tQRATLiYPFCwE+Vu8BJ1AY/fgR5CTMppOHgD4OPeMo707vIfhb8d+Chfy3z9+DHBulDY9IiCU78GA5fhJqXWllPxHa2pmxnMm3km1DF6LBHcq5Nmhc6YyTSNHROilL/FdDhJkYoo/wUms2XdIs8PiKSL9SzsoXXcFP/ey9f2SnhKYdOIxWm/7UXWcCyZI2O1et57VDOyiBmnRO3yrNMiTO7lMMnlPXlakPRp2s1F/ldsZKde2+bYvxHSu6iXRzxkCl9Df0Y4RfwKLuiyE/D4DXykYPsltSuJrGV6c3oASIdFdPsnmTCapwX5UV4gXGMl9IuLBmhtbrIWXvRWrxxqQRCeRb1HOtWAqNasA7wQTLNnVRyWR5sfdgsQK7tff2srjlJZniTitOs0y39Guy7BUXbZhI4+EFByHaPIw2ayvGv+ZnvhqxXMSlMwY/nhz2Lh5lZ8sZvS1221y8g0ft0zUZedIKMppvxuxQH/DinpPeWkUhMM1Yb9aNoSLmc8LrOXnsThUnBw1yVnLEQgr+Lfc+/ryqyIOUW0aSkNB4S20B+Ag=
